---
# Install Couchbase Server
- hosts: all
  any_errors_fatal: true

  vars:
    couchbase_server_package_url: "{{ couchbase_server_package_base_url }}/{{ couchbase_server_package }}"

  tasks:
  # Remove server package
  - name: Couchbase Server | Uninstall server msi
    win_command: wmic product where name='Couchbase Server' call uninstall
    register: unintall_output

  - debug: 
        var: unintall_output.stdout
        verbosity: 2

  # Delete server binary
  - name: Couchbase Server | Delete server install directory
    win_file:
        path: "C:\\Program Files\\Couchbase"
        state: absent
        when: "unintall_output.rc == 0"

  # Download server package
  - name: Couchbase Server |  Download server exe "{{ couchbase_server_package_url }}"
    win_get_url:
        url: "{{ couchbase_server_package_url }}"
        dest: "C:\\Users\\Administrator\\AppData\\Local\\Temp\\{{ couchbase_server_package }}"

  # Install server service msi
  - name: Couchbase Server | Install server msi "{{ couchbase_server_package }}"
    win_package:
       path: "C:\\Users\\Administrator\\AppData\\Local\\Temp\\{{ couchbase_server_package }}"
       creates_path: "C:\\Program Files\\Couchbase"
       state: present
