---
# Install Couchbase Server
- hosts: all
  any_errors_fatal: true

  vars:
    couchbase_server_package_url: "{{ couchbase_server_package_base_url }}/{{ couchbase_server_package }}"

  tasks:
  # Remove server package
  - name: Couchbase Server | Uninstall cb server msi
    win_command: wmic product where name='Couchbase Server' call uninstall
    register: cb_uninstall_output

  - debug: var=cb_uninstall_output.stdout_lines

  # Remove server analytic package
  - name: Couchbase Server | Uninstall cb server analytics msi
    win_command: wmic product where name='Couchbase Server Analytics' call uninstall
    register: uninstall_output

  - debug: var=analytic_uninstall_output.stdout_lines

  # Delete server binary
  - name: Couchbase Server | Delete server install directory
    win_file:
        path="C:\Program Files\Couchbase"
        state=absent
        ignore_errors=yes

  # Download server package
  - name: Couchbase Server |  Download server exe "{{ couchbase_server_package_url }}"
    win_get_url:
        url={{ couchbase_server_package_url }}
        dest=C:\Users\Administrator\AppData\Local\Temp\{{ couchbase_server_package }}

  # Install server service msi
  - name: Couchbase Server | Install server msi "{{ couchbase_server_package }}"
    win_package:
       path=C:\Users\Administrator\AppData\Local\Temp\{{ couchbase_server_package }}
       state=present
